[project]
name = "arm-grab"
version = "1.0.0"
description = "script to try to grab one of the sweet free ARM instances from Oracle"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["oci>=2.150.2"]
